backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images/"
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Przepisy" # Used in the UI
    folder: "src/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nazwa potrawy", name: "title", widget: "string"}
      - {label: "Data opublikowania", name: "date", widget: "date", format: 'DD-MM-YYYY'}
      - {label: "Zdjęcie potrawy", name: "img", widget: "image"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Sposób przygotowania", name: "body", widget: "markdown"}
      - label: "Składniki"
        name: "ingredients"
        widget: "list"
        min: 1